name: Execute ls and push to main

on:
  push:
    branches:
      - main

jobs:
  execute_ls_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Commit changes
      env:
        DEPLOY_PRI: ${{ secrets.DEPLOY_PRI }}
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        mkdir -p ~/.ssh/
        echo "$DEPLOY_PRI" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        ls img/ > img.txt
        cat img.txt
        pwd
        ls -a
        sh "${GITHUB_WORKSPACE}/.github/script/push.sh"

